sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: QrxuPpjTiD0/odMiILwyx9atuCBDVDpJ+0rE2/Odg9Ol5m4uSzv/bRRJl64v8rBd1weOqdRd61/9mFz0bhrapuxF0iOIGRAvFX9uNU+P7gAPQxkroP3X/w2vI0kdJqydDg/BoIfW/CapNj6VgTL29SQw8YOc5StHwZRW3saN6EAUumS0OKTWQXZroXiQW5vp8OL9taYLndQbQ+Dk7UUVat1CDrsgonqIVQoc1oub8aOC4SV8rrm823Qw9qkdBxr84Ha76CSaVtQY/mwOTRri9Xo6fgc0rXo2SZrpgGwsJQEj5jvNvN4fiTA1luwBwbB8QeRo74q7/S3DBKYYcAjb+QZz3RP72Hj4dc/ROSRc9RKOX1ukmzl2YtdZcLHiWUwtUMMGMAUfAOqZE7y7HU9MYT/dd021TrkqdSUXDzIc9FyLPXnjp73UzEPoLer2F8yQnhdnJlJRpSAz+T/uZrzkrJcEn1FdpPavIqbGOivvoGsDgaJ3X8i6NW6guu+gHshh1RH23julTRbsw/57endGMSqBv76QFOw1840lFXcTy8wkKsdWFqWoSQCRN1OxSwzw2Ltc4LPgsFp7wYh7ZlKEesgKvxBIFJDAfFxq7nzzb79uyUQR0eGnkwVIF8E+4ob2slbBXPmIfcC/JD8+97RxTSkCneHZrxlTUdr7ap999/s=
